env.name=Development
db.url=jdbc:mysql://localhost:3306/dev_db
logging.level=DEBUG
feature.payment=false
pipeline.init=true
pipeline.config=true
pipeline.db=true
pipeline.logging=true
pipeline.services=true