env.name=Production
db.url=jdbc:mysql://prod-server:3306/prod_db
logging.level=ERROR
feature.payment=true
pipeline.init=true
pipeline.config=true
pipeline.db=true
pipeline.logging=true
pipeline.services=true