env.name=Testing
db.url=jdbc:mysql://localhost:3306/test_db
logging.level=WARN
feature.payment=true
pipeline.init=true
pipeline.config=true
pipeline.db=true
pipeline.logging=true
pipeline.services=true